### ISSUE TITLE
Open to PRs ?

### ISSUE THREAD

**Issue by ben-j69** [Chrisvin/EasyReveal#2]
Hello, I might use your library in my app, are you open to pull request to make some fixes in typos and code/dependencies updates?

**Comment by Chrisvin** [comment]
Yes, I'm open to PRs.
But note that `EasyReveal` was designed with extensibility in mind. If you want to customize the base structure (say, as done in `LiquidSwipe`), I might not necessarily approve the changes.
In which case, I'd suggest you use your own forked & customized version in your app.
