### ISSUE TITLE
Reveal function not playing animation

### ISSUE THREAD

**Issue by 24Lathiya** [Chrisvin/EasyReveal#4]
I would like to play animation on start my activity. so did coding like below.

```
EasyRevealLinearLayout revealLinearLayout = findViewById(R.id.revealLayout);
revealLinearLayout.setClipPathProvider(new LinearClipPathProvider(LinearClipPathProvider.Direction.BOTTOM_TO_TOP));
revealLinearLayout.setRevealAnimationDuration(2000);
revealLinearLayout.reveal();
```

but it wan't animation view. if i do same thing on click it was worked fine.
@Chrisvin please let me know what was missed.

hide method work properly with below `code`

```
EasyRevealLinearLayout revealLinearLayout = findViewById(R.id.revealLayout);
revealLinearLayout.setClipPathProvider(new LinearClipPathProvider(LinearClipPathProvider.Direction.BOTTOM_TO_TOP));
revealLinearLayout.setHideAnimationDuration(2000);
revealLinearLayout.hide();
```

and please let me know how to replay animation on finish?
Please help. Thanks.

**Comment by Chrisvin** [comment]
The issue is that the view is already in revealed state. It first needs to be hidden (without animation using `revealForPercentage(0, false)`) before `reveal()` is called. The following code should work,
```
EasyRevealLinearLayout revealLinearLayout = findViewById(R.id.revealLayout);
        
revealLinearLayout.revealForPercentage(0f, false);
        
revealLinearLayout.setClipPathProvider(new LinearClipPathProvider(LinearClipPathProvider.Direction.BOTTOM_TO_TOP));
revealLinearLayout.setRevealAnimationDuration(2000);
revealLinearLayout.reveal();
```

There is no inbuilt method to replay animation, but you can use `postDelayed` or any other delay mechanism to time your reveal/hide calls. Something along the following lines should work,
```
revealLinearLayout.reveal();

revealLinearLayout.postDelayed(new Runnable() {
    @Override
    public void run() {
        revealLinearLayout.hide();
    }
}, 2000);
```

**Comment by bryan-ibrahim** [comment]
Pasted the exact same code & it still doesn't work
